name: Playwright Smoke Tests
on: [push, pull_request] # Runs the workflow on push and pull requests.

jobs:
  test:
    runs-on: ubuntu-latest # Uses the latest Ubuntu-based virtual machine.
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Retrieves the latest code from the repository.

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Installs Node.js version 18.

      - name: Install Dependencies
        run: npm ci # Installs project dependencies.

      - name: Install Playwright Browsers
        run: npx playwright install # Installs the necessary browsers for Playwright tests.

      - name: Debug Environment
        run: env # Prints environment variables for debugging.

      - name: Run Smoke Tests with X Server
        run: xvfb-run --auto-servernum npx playwright test -g "@smoke" --reporter=allure-playwright
        # Runs smoke tests tagged with "@smoke", using an X server for headless browser support.
        # The Allure Playwright reporter generates the raw results.

      - name: Download Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.23.0/allure-2.23.0.tgz -O allure-2.23.0.tgz
          tar -xzf allure-2.23.0.tgz
          echo "$(pwd)/allure-2.23.0/bin" >> $GITHUB_PATH
        # Downloads Allure CLI archive and extracts it.
        # Adds the Allure binary path to the system PATH for subsequent steps.

      - name: Check Allure Installation
        run: allure --version
        # Confirms that Allure is installed and prints its version for verification.

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report/
        # Processes raw Allure results from the allure-results directory into the allure-report folder.

      - name: Check Allure Report Files
        run: ls -la allure-report/
        # Lists the contents of the generated Allure report directory for debugging.

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
        # Uploads the generated Allure report as an artifact for further inspection.